spring.application.name:
  LivingAssistantBackEnd

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.121.124.247:3306/mobile_assistant
    username: LiuYun
    password: 123456

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml  # 指定 Mapper XML 文件位置，如果没有 XML 文件可省略
  type-aliases-package: com.ly.livingassistantbackend.pojo  # 指定实体类所在包
  global-config:
    db-config:
      id-type: auto  # 设置主键策略为自增
      logic-delete-field: deleted  # 设置逻辑删除字段
      logic-not-delete-value: 0  # 未删除标志
      logic-delete-value: 1  # 已删除标志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL 日志，开发时方便调试